### ISSUE TITLE
RGB Server Needs

### ISSUE THREAD

**Issue by BitcoinErrorLog** [LNP-BP/devcalls#6]
- Need min specs for server for RGB/LN testing
- Do we need a separate server for hosting RGB website and mail forwarding?

**Comment by dr-orlovsky** [comment]
1. 16GB RAM, 8 cores, 2GB drive (SSD preffered, but HDD will work)
2. No, static web sites can be easily hosted with GitHub Pages or  Google Firebase for free. Also I prefer not to have web stuff in the same place as nodes.

**Comment by BitcoinErrorLog** [comment]
Noted, will bring this up with Paolo today.
