### ISSUE TITLE
RGB Roadmap

### ISSUE THREAD

**Issue by BitcoinErrorLog** [LNP-BP/devcalls#8]
Are we keeping a public roadmap of any form, here, or on the new website? Is there a current version? It might be nice to communicate the priority of things and reasonable milestones, etc.

**Comment by MaxHillebrand** [comment]
There are several project boards for different parts of the effort [here](https://github.com/orgs/LNP-BP/projects).

**Comment by dr-orlovsky** [comment]
Superseded by https://github.com/LNP-BP/devcalls/issues/29
